In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
%matplotlib
%matplotlib inline

file_name = "pisa2012.csv"
columns = ['CNT', 'PV1MATH', 'ST04Q01', 'ANCCLSMAN','MMINS','ST55Q02','ANCMATWKETH','DISCLIMA','WEALTH']
df_raw = pd.read_csv(file_name, sep=',',encoding = 'iso-8859-1', usecols=columns)

Using matplotlib backend: Qt5Agg

In [31]:
no_significant_extra_math=['2 or more but less than 4 hours a week',
                           '4 or more but less than 6 hours a week',
                           '6 or more hours a week']

df_raw['Extra math classes'] = np.where(df_raw['ST55Q02']==no_significant_extra_math[0],1.0,0.0)
df_raw['Extra math classes'] = np.where(df_raw['ST55Q02']==no_significant_extra_math[1],1.0,df_raw['Extra math classes'])
df_raw['Extra math classes'] = np.where(df_raw['ST55Q02']==no_significant_extra_math[2],1.0,df_raw['Extra math classes'])

df_raw.head()

,CNT,ST04Q01,ST55Q02,DISCLIMA,MMINS,WEALTH,ANCCLSMAN,ANCMATWKETH,PV1MATH,Extra math classes
0,Albania,Female,NaN,1.85,NaN,-2.92,-0.7808,-0.2199,406.8469,0.0
1,Albania,Female,2 or more but less than 4 hours a week,NaN,270.0,0.69,NaN,NaN,486.1427,1.0
2,Albania,Female,2 or more but less than 4 hours a week,NaN,NaN,-0.23,NaN,NaN,533.2684,1.0
3,Albania,Female,I do not attend <out-of-school time lessons> i...,1.80,135.0,-1.17,NaN,NaN,412.2215,0.0
4,Albania,Female,NaN,-0.08,NaN,-1.17,0.0505,0.9341,381.9209,0.0

In [36]:

df=df_raw

# countries=['Denmark', 
#            'Sweden', 
#            'Norway', 
#            'New Zealand', 
#            'Switzerland', 
#            'Australia', 
#            'Canada', 
#            'Iceland', 
#            'Finland']

# df=df_raw[df_raw['CNT'].isin(countries)].dropna(axis=0)

In [37]:
# file_name_save="Pisa2012_filtered.csv"
# df.to_csv(file_name_save, sep=',')

In [38]:
df_country = df.groupby(['CNT'],as_index=False)['PV1MATH', 'MMINS','ANCCLSMAN','Extra math classes','ANCMATWKETH','DISCLIMA', 'WEALTH'].mean()
df_country = df_country.rename(columns={'CNT':'Country',
                                                    'PV1MATH':'Mean math test score', 
                                                    'ANCCLSMAN':'Mean math teacher management',
                                                    'DISCLIMA': 'Mean classroom Discipline',
                                                    'ANCMATWKETH':'Mean math work ethic',
                                                    'WEALTH':"Mean household wealth",
                                                    "MMINS":"Mean time spent on math (minutes)"})

In [39]:
min_value = df_country['Mean household wealth'].min()
max_value = df_country['Mean household wealth'].max()

df_country_scaled=df_country.copy()
df_country_scaled['Mean household wealth']=(df_country['Mean household wealth']-min_value) / (max_value - min_value)

file_name_save="Pisa2012_country_mean_scaled.csv"
df_country_scaled.to_csv(file_name_save, sep=',', index=False)
df_country_scaled

,Country,Mean math test score,Mean time spent on math (minutes),Mean math teacher management,Extra math classes,Mean math work ethic,Mean classroom Discipline,Mean household wealth
0,Albania,395.296185,171.165197,0.041939,0.189964,0.074302,0.386653,0.368676
1,Argentina,395.402241,278.499787,-0.325183,0.096310,-0.178049,-0.492073,0.479227
2,Australia,492.842855,235.801302,0.143663,0.071542,0.117230,-0.172390,0.893166
3,Austria,507.711753,155.840096,-0.054778,0.053207,0.055561,0.225156,0.824417
4,Belgium,519.868902,216.420305,0.048089,0.109689,0.060170,0.069513,0.777333
5,Brazil,382.500793,209.512773,-0.160014,0.245938,-0.001707,-0.332248,0.386418
6,Bulgaria,442.158361,133.700064,-0.166796,0.114161,-0.239286,-0.190041,0.603466
7,Canada,509.328982,303.558580,0.200072,0.083132,0.209622,-0.022923,0.896857
8,Chile,444.419644,381.258030,-0.034638,0.145858,0.070473,-0.193701,0.659284
9,China-Shanghai,610.547030,269.699209,0.483398,0.305582,0.499965,0.577947,0.501374
10,Chinese Taipei,557.576851,241.805520,-0.049716,0.265630,-0.256342,-0.001784,0.595238
11,Colombia,386.185442,267.739902,0.050149,0.139425,0.091328,-0.028621,0.307680
12,Connecticut (USA),501.166969,234.524790,0.296249,0.067767,0.432951,0.273494,0.953764
13,Costa Rica,406.093702,208.037882,0.226837,0.145372,0.350691,0.035637,0.326195
14,Croatia,469.833121,146.796117,-0.052367,0.101038,-0.127535,-0.126372,0.602215
15,Czech Republic,519.774978,183.576077,-0.012255,0.095363,-0.205260,0.111058,0.682058
16,Denmark,486.185453,228.955571,0.007155,0.160540,0.101142,-0.045522,0.800535
17,Estonia,521.805050,223.254248,0.129580,0.121783,-0.022988,0.185977,0.685719
18,Finland,507.525776,174.906896,-0.042812,0.165704,-0.107306,-0.304364,0.805476
19,Florida (USA),464.957491,248.754653,0.236951,0.092827,0.317700,-0.001909,0.888184
20,France,499.470436,207.698367,-0.063796,0.114242,-0.009189,-0.284067,0.786617
21,Germany,513.932189,196.125978,-0.008523,0.063987,0.061133,-0.022313,0.802882
22,Greece,453.890068,209.129098,-0.202360,0.266732,-0.157035,-0.256360,0.662565
23,Hong Kong-China,561.274096,266.482818,0.057669,0.153961,0.045463,0.283334,0.444013
24,Hungary,485.390840,149.152995,-0.140154,0.070270,-0.200775,0.077221,0.581962
25,Iceland,493.147077,243.494533,0.164517,0.107469,0.216041,-0.025473,0.872845
26,Indonesia,376.071790,210.870290,-0.344987,0.153860,-0.092741,0.128225,0.000000
27,Ireland,500.903629,188.835830,0.205387,0.056619,0.221362,0.120537,0.879625
28,Israel,468.885822,253.130515,0.050856,0.174481,0.111107,0.273156,0.703086
29,Italy,491.904167,229.052812,-0.107351,0.186239,-0.053662,-0.035611,0.769672
...,...,...,...,...,...,...,...,...
38,Macao-China,538.313046,275.151698,0.115188,0.152765,0.103215,0.100921,0.577493
39,Malaysia,422.788401,201.748921,-0.202631,0.265345,-0.128325,-0.192850,0.423587
40,Massachusetts (USA),506.372066,294.792784,0.262730,0.073709,0.379795,0.294673,0.898270
41,Mexico,418.634889,253.524591,0.041776,0.156097,0.074704,0.063872,0.331980
42,Montenegro,406.397444,142.999670,-0.051116,0.101180,-0.123701,0.001132,0.603463
43,Netherlands,518.133386,169.630930,0.024896,0.085650,0.075396,-0.178184,0.811077
44,New Zealand,501.390671,240.175681,0.094842,0.074342,0.086885,-0.242299,0.794519
45,Norway,489.752776,199.912332,-0.069497,0.084720,-0.013430,-0.081582,0.953721
46,Perm(Russian Federation),487.163724,221.936494,0.165011,0.249290,-0.110899,0.235834,0.483130
47,Peru,367.810655,285.890345,0.031514,0.296272,0.104400,-0.029309,0.201018
48,Poland,520.592926,199.309037,-0.188092,0.081832,-0.225872,0.065895,0.686064
49,Portugal,484.559765,293.379438,0.022403,0.228766,0.095000,0.026386,0.812997
50,Qatar,376.761703,258.543353,-0.432709,0.210378,-0.185379,-0.322183,1.000000
51,Romania,445.797146,167.727721,-0.344748,0.151951,-0.481611,0.008267,0.457112
52,Russian Federation,482.702942,222.674419,0.186605,0.231504,-0.092789,0.316724,0.518904
53,Serbia,447.735377,153.771399,-0.145501,0.146029,-0.199315,-0.158865,0.586471
54,Singapore,568.359669,284.563094,0.245641,0.313559,0.297986,0.202840,0.621354
55,Slovak Republic,485.644734,178.650767,-0.206561,0.072039,-0.497227,-0.127589,0.619090
56,Slovenia,484.481209,156.494627,-0.265512,0.067670,-0.312687,-0.032053,0.813078
57,Spain,495.359865,208.148691,-0.087425,0.183028,0.029121,-0.026668,0.734836
58,Sweden,479.152938,181.493379,-0.040782,0.114865,0.005350,-0.195059,0.863580
59,Switzerland,520.672206,221.421584,-0.017144,0.083712,-0.075159,0.050123,0.758155
60,Thailand,441.147091,212.221565,-0.198797,0.267181,-0.081223,0.069314,0.413913
61,Tunisia,387.279745,276.373547,-0.137122,0.352621,-0.084820,-0.422515,0.205360
62,Turkey,448.833618,170.780632,-0.124103,0.146658,-0.100818,-0.077602,0.265287
63,United Arab Emirates,431.373626,296.731890,-0.107982,0.205217,0.141574,-0.005001,0.918186
64,United Kingdom,489.645545,230.146636,0.185894,0.137136,0.265404,0.133338,0.841118
65,United States of America,481.032476,254.948685,0.244395,0.084170,0.376447,0.048729,0.905464
66,Uruguay,410.957687,156.538776,-0.094066,0.117780,-0.040850,-0.160525,0.517493
67,Vietnam,510.589967,226.802486,0.070789,0.431539,0.020190,0.372836,0.082277

In [21]:
# plt.style.use('seaborn-muted')
# df_country_mean.plot(
#     kind='bar',
#     title='Mean Math',
#     stacked=True)